export const ProductData = [
  {
    url: "/product-details",
    image: "/images/products/1.webp",
    title:
      "Necklace, Earring & Ring Set Water Drop White Necklace, Earring & Ring Set...",
    productType: "28 ml",
    productPrice: "350",
    discountPrice: "300",
    discountType: "",
    offerType: "10.00%",
    appPrice: "315",
    isButton: false,
  },
  {
    url: "/product-details",
    image: "/images/products/2.webp",
    title:
      "Earring ( Kolki Yellow)Earring ( Kolki Yellow)Earring ( Kolki Yellow)...",
    productType: "28 ml",
    productPrice: "350",
    discountPrice: "300",
    discountType: "Save 65%",
    offerType: "10.00%",
    appPrice: "315",
    isButton: false,
  },
  {
    url: "/product-details",
    image: "/images/products/3.webp",
    title:
      "Ear Top (Stone Dandelion)Ear Top (Stone Dandelion)Ear Top (Stone Dandelion)...",
    productType: "28 ml",
    productPrice: "350",
    discountPrice: "300",
    discountType: "Save 65 TK",
    offerType: "10.00%",
    appPrice: "315",
    isButton: true,
  },
  {
    url: "/product-details",
    image: "/images/products/4.webp",
    title:
      "J.Cat Sparkling Powder (Cool Silver)J.Cat Sparkling Powder (Cool Silver)...",
    productType: "28 ml",
    productPrice: "350",
    discountPrice: "300",
    discountType: "Flat 50 Tk Discount",
    offerType: "10.00%",
    appPrice: "315",
    isButton: true,
  },
  {
    url: "/product-details",
    image: "/images/products/5.webp",
    title:
      "Necklace, Earring & Ring Set Water Drop White Necklace, Earring & Ring Set...",
    productType: "28 ml",
    productPrice: "350",
    discountPrice: "300",
    discountType: "Save 65%",
    offerType: "10.00%",
    appPrice: "315",
    isButton: false,
  },
  {
    url: "/product-details",
    image: "/images/products/6.webp",
    title:
      "Earring ( Kolki Yellow)Earring ( Kolki Yellow)Earring ( Kolki Yellow)...",
    productType: "28 ml",
    productPrice: "350",
    discountPrice: "300",
    discountType: "",
    offerType: "10.00%",
    appPrice: "315",
    isButton: false,
  },
  {
    url: "/product-details",
    image: "/images/products/7.webp",
    title:
      "Ear Top (Stone Dandelion)Ear Top (Stone Dandelion)Ear Top (Stone Dandelion)...",
    productType: "28 ml",
    productPrice: "350",
    discountPrice: "300",
    discountType: "",
    offerType: "10.00%",
    appPrice: "315",
    isButton: false,
  },
  {
    url: "/product-details",
    image: "/images/products/8.webp",
    title:
      "J.Cat Sparkling Powder (Cool Silver)J.Cat Sparkling Powder (Cool Silver)...",
    productType: "28 ml",
    productPrice: "350",
    discountPrice: "300",
    discountType: "",
    offerType: "10.00%",
    appPrice: "315",
    isButton: false,
  },
];
